### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [SaBuZa/RTSdynamicGA_Prototype#3]
Hello, under what license is this project released under ? I would like to study it to learn from it. Thank you.

**Comment by SarotBu** [comment]
Hi ! Thank you for the interest !
Let’s take it as MIT License.

A bit disclaimer on the code is that if I remember correctly, it had heavy problem in concurrency part and the code does not really work properly. It is runnable though but the outcome from the algorithm, though have some kind of visible improvement, is quite skeptical.
This implementation is very rough following the original paper experimented with RPG setting without adapting to RTS style and the SC2 game environment at all so it maybe much better to check the original papers. (I think this code implement with mixed ideas from original Dynamic scripting algorithm paper + Genetic algorithm with RPG setting)

Sorry for the mess in the code. Thank you again for your interest !

Sincerely,
Sarot Busala

**Comment by suprafun** [comment]
Thank you so very much. Would it be possible for you to upload a formal license to the repo. ? I ask so I can be sure of how to treat it and it would help others. It seems like a very cool project to learn from. Thank you again.

**Comment by SarotBu** [comment]
I just uploaded the license. Thank you very much for your interest !

**Comment by suprafun** [comment]
Thank you so very much 😃
